# Generated by Django 5.0.6 on 2024-05-16 13:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=2,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
            ],
        ),
    ]
